main:
    path: /
    controller: App\Controller\MainController::index
ad-list:
    path: /ad-list
    controller: App\Controller\AdController::list
add-ad:
    path: /add-ad
    controller: App\Controller\AdController::add
show-ad:
    path: /show-ad/{id}
    controller: App\Controller\AdController::show
